repoLabels:

  - name: Refactor
    color: "5319e7"
    description: Refactor a piece of code

  - name: brainstorming
    color: F50884
    description: Thinking real hard

  - name: bug
    color: EE1111
    description: Something isn't working

  - name: deferred
    color: D2984D
    description: Work will resume in due course

  - name: documentation
    color: 0e8a16
    description: Improvements or additions to documentation

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: enhancement
    color: 1d76db
    description: New feature or request

  - name: focus
    color: d93f0b
    description: Critical / High-Priority / Currently-in-Focus

  - name: good first issue
    color: A5F45C
    description: Good for newcomers

  - name: help wanted
    color: "008672"
    description: Extra attention is needed

  - name: invalid
    color: d73a4a
    description: This doesn't seem right

  - name: marked for review
    color: 006b75
    description: Revisit and re-examine later

  - name: question
    color: fbca04
    description: Further information is requested

  - name: wontfix
    color: "000000"
    description: This will not be worked on
